import { type Problem } from './types';

export const mockProblems: Problem[] = [
  {
    id: 1,
    platform: 'LeetCode',
    platformIcon: '◼️',
    title: 'Longest Common Subsequence',
    tags: ['dynamic programming', 'strings', 'greedy', 'recursion'],
    difficulty: 'High',
    link: '',
  },
  {
    id: 2,
    platform: 'Codeforces',
    platformIcon: '📊',
    title: 'Edit Distance',
    tags: ['dynamic programming', 'graphs', 'graphs'],
    difficulty: 'High',
    link: '',
  },
  {
    id: 3,
    platform: 'AtCoder',
    platformIcon: '🐜',
    title: 'Traveling Salesman',
    tags: ['dynamic programming', 'strings', 'greedy'],
    difficulty: 'Medium',
    link: '',
  },
  {
    id: 4,
    platform: 'CodeChef',
    platformIcon: '🍳',
    title: 'Longest Connection',
    tags: ['dynamic programming', 'graphs', 'greedy'],
    difficulty: 'High',
    link: '',
  },
  {
    id: 5,
    platform: 'CodeChef',
    platformIcon: '🍳',
    title: 'Traveling Pattern',
    tags: ['dynamic programming', 'greedy', 'recursion', 'recursion'],
    difficulty: 'High',
    link: '',
  },
  {
    id: 6,
    platform: 'Codeforces',
    platformIcon: '📊',
    title: 'Longest Subsequence',
    tags: ['dynamic programming', 'greedy', 'recursion', 'graphs'],
    difficulty: 'High',
    link: '',
  },
  {
    id: 7,
    platform: 'CodeChef',
    platformIcon: '🍳',
    title: 'Monestriatic Function',
    tags: ['dynamic programming', 'strings', 'greedy'],
    difficulty: 'High',
    link: '',
  },
  {
    id: 8,
    platform: 'CodeChef',
    platformIcon: '🍳',
    title: 'Traveling Salesman',
    tags: ['dynamic programming', 'greedy', 'recursion', 'graphs'],
    difficulty: 'High',
    link: '',
  },
  {
    id: 9,
    platform: 'CSES',
    platformIcon: '🔷',
    title: 'Longest Common Subsequence',
    tags: ['dynamic programming', 'strings', 'greedy', 'recursion'],
    difficulty: 'High',
    link: '',
  },
  {
    id: 10,
    platform: 'CSES',
    platformIcon: '🔷',
    title: 'leetcode.com/problems/...65561/...',
    tags: ['dynamic programming', 'recursion', 'greedy', 'recursion'],
    difficulty: 'Medium',
    isNew: true,
    link: '',
  },
];
